[SQCY-417] DS | Drawer
HumandDev/material-hu pull request #117
Opened 2024-11-04 13:55 UTC by LucasZibell

## Summary
Se suma el componente Drawer

## Screenshots, GIFs or Videos
<img width="1215" alt="Screenshot 2024-11-04 at 10 55 06" src="https://github.com/user-attachments/assets/9734733c-3683-4436-a526-05b7d03dd7db">

## Jira Card
[Card](https://humand.atlassian.net/browse/SQCY-417)

2024-11-05 13:18 UTC, dgarcia-hu requested changes

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +  secondaryAction?: () => void;
Lo haría como lo tenemos en el Dialog, así mantenemos convenciones.

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +  extraFooterContent?: ReactNode;
Considerando que las actions están como actions y no como footer, a este le pondría `footer` directamente. Para simplificar.

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +  secondaryLayoutContent?: ReactNode;
Hace falta el `withDoubleLayout`? No se puede saber si se quiere el doble layout viendo si nos pasaron `secondaryLayoutContent`?

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +  secondaryLayoutContent?: ReactNode;
Una boludez, pero tal vez les pondría `primaryContent` y `secondaryContent`, me parecen entendibles y más simples.

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +    <MuiDrawer
Estaría bueno esto tenerlo en un `useDrawer`, igual que como tenemos con los dialogs. Hay un hook así en `src/hooks/useDrawer` de backoffice.

2024-11-05 13:18 UTC, dgarcia-hu commented on src/components/Drawer/Drawer.tsx
> +      <Stack
Por la foto que pusiste le veo estilos muy diferentes a los que se tienen en el diseño del figma. :thinking:

2024-11-11 12:13 UTC, dgarcia-hu requested changes

2024-11-11 12:13 UTC, dgarcia-hu commented on src/hooks/useDrawer.tsx
> +      <Drawer
Habría que ver una forma en el que el `Drawer` no quede duplicado. Porque actualmente está acá y está en el componente nuevo que se hizo, así que si se usa el nuevo componente con este hook va a quedar un `Drawer` dentro del otro.
Creo que lo sacaría del componente nuevo y lo dejaría acá, para mantenerlo con las convenciones de lo que se hizo para el Dialog.

2024-11-11 12:13 UTC, dgarcia-hu commented on src/theme/hugo/components.ts
> +        minWidth: '200px',
Esto se lo cambió desde diseño? Al menos en el figma se mantiene con el 256, pero tal vez lo hablaron y acordaron cambiarlo, por eso pregunto.
Lo mismo para el cambio de `fontWeightSemiBold`.

2024-11-11 13:56 UTC, LucasZibell commented on src/theme/hugo/components.ts
> +        minWidth: '200px',
Sisi, el cambio de semiBold se hizo porque no existe el weight `600` en esta font, entonces nosotros vamos a usar `500`
Lo del boton si tambien, hable con Mer y me dijo que bajemos el tamaño del boton large porque con 256 no entraba en el drawer en todas las resoluciones. Ella se lo llevo para ver y me confirmo bajar el tamaño del large button a 200px en todos los componentes. Para que se banque bien en pantallas de 1200px

2024-11-11 14:35 UTC, dgarcia-hu approved these changes

2024-11-11 14:39 UTC, dgarcia-hu approved these changes

2024-11-11 15:36 UTC, merged