DS3 | Dropdown
HumandDev/material-hu pull request #118
Opened 2024-11-04 16:16 UTC by fgorostiaga-hu

## Summary
El component puede ser uncontrolled o controlled, dependiendo si se quiere mantener el estado de `open` como comportamiento interno del componente o ser manejado desde el componente padre.

## Screenshots, GIFs or Videos
![image](https://github.com/user-attachments/assets/1097815c-7574-4958-be8f-1f1233abe68f)

## Jira Card
[Card](https://humand.atlassian.net/browse/SQPD-1496)

2024-11-05 13:37 UTC, dgarcia-hu requested changes

2024-11-05 13:37 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.stories.tsx
> +      <List sx={{ width: '300px' }}>
Tal vez con cosas como `List` que ya están hechas en HuGo, las empezaría a usar en las stories también, en vez de las de material. Así ya va quedando hasta las stories con HuGo.

2024-11-05 13:37 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +  buttonProps?: ButtonProps;
Considerando que ya se tiene un `buttonProps` acá, hace falta tener por separado el `buttonType` y el `buttonSize`?
Edit: ahí ví que el `Button` actual no tiene las propiedades definidas como se espera en el figma. Yo diría que por ahora lo dejes solo con el `buttonProps` y agarremos para hacer `Button` como está definido en el figma.

2024-11-05 13:37 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
Considerando que ya tenemos el `sx` que va al wrapper, sacaría el `popoverSx`. Total se debería poder llegar a él desde el `sx`.

2024-11-05 13:37 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +      <Popover
En el figma veo que están usando el `Menu` de HuGo, en vez de un `Popover`. Tal vez mejor usar directamente ese que tiene el diseño ya armado. Y lo del mappeo de dónde se quiere abrir lo movería al `Menu`.

2024-11-05 13:37 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +  const containedButtonSx = {
Me confunde porqué hay estilos del button contained acá. Eso no debería estar definido en el componente `Button` directamente?

2024-11-05 15:20 UTC, fgorostiaga-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
Si pero se hace mas rebuscado a mi parecer. Teniendo el `popoverSx` es mas directo y queda mas claro el codigo, no tenes que estar seleccionando clases anidadas. En muchos componentes nativos de MUI se hace asi. Que opinas de dejarlo?

2024-11-05 15:22 UTC, fgorostiaga-hu commented on src/components/Dropdown/Dropdown.tsx
> +  const containedButtonSx = {
Es lo que mencionas antes, el componente `Button` no tiene las propiedades/estilos que espera el diseño, por lo que tengo que editarlas "a mano".

2024-11-05 16:47 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
La verdad no lo he visto usado en los componentes nativos de MUI.
Yo porque tenía entendido que la idea es en principio usar los componentes de HuGo tocando lo menos posible sus estilos, osea, no se qué tan seguido se quiera cambiar el sx del popover. A no ser que sea algo recurrente no me parece tan grave usarlo con el sx principal.

2024-11-05 18:06 UTC, fgorostiaga-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
No como sxProps pero si como props de un componente interno. Por ej., el Menu tiene `MenuListProps`, `slotProps`, `TransitionProps` para poder pisar o cambiar las propiedades default de estos componentes internos. Siguiendo esto podria poner la prop PopoverProps en vez de popoverSx. Entiendo que la idea es tocar lo menos posible de los componentes de HuGo pero siempre esta bueno tener mas flexiblidad, por si las moscas...

2024-11-05 18:15 UTC, fgorostiaga-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
Igual todo depende de si usamos el Popover o el Menu. En caso de usar el Menu no hay nada que resolver :)

2024-11-06 13:05 UTC, dgarcia-hu commented on src/components/Dropdown/Dropdown.tsx
> +  popoverSx?: SxProps;
Dale, me parece mejor entonces poner PopoverProps de última.

2024-11-06 19:30 UTC, dgarcia-hu approved these changes

2024-11-06 19:57 UTC, merged